name: 🕵️ Secret Scanning

on:
  pull_request:
    branches:
      - main
      - master
      - feature/**
      - fix/**
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  gitleaks:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for comprehensive scanning

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Optional: for advanced features

      - name: Upload scan results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          retention-days: 7

      - name: Annotate PR with findings
        if: failure() && github.event_name == 'pull_request'
        run: |
          echo "❌ Potential secrets detected in code!"
          echo "Please review the findings and remove any sensitive data."
          echo "Common issues:"
          echo "  - API keys"
          echo "  - Passwords or tokens"
          echo "  - Private keys"
          echo "  - AWS credentials"
          exit 1

      - name: Success message
        if: success()
        run: echo "✅ No secrets detected in code"
